
#pragma once


#ifndef AP_THRUST_STAND_ENABLED
#define AP_THRUST_STAND_ENABLED 1
#endif

#define AP_NETWORKING_THRUST_STAND_ENABLED AP_THRUST_STAND_ENABLED

#if AP_NETWORKING_THRUST_STAND_ENABLED
#ifndef AP_NETWORKING_THRUST_STAND_IP
#define AP_NETWORKING_THRUST_STAND_IP "192.168.2.102"
#endif
#endif

#define THRUST_STAND_RECV_BUFFER_SIZE 1024