#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.ap_stlib(
        name='AP_VTOL_MPC',
        target='AP_VTOL_MPC',
        source=[
            'AP_VTOL_MPC.cpp',
        ],
        use=[
            'AP_Common',
            'AP_HAL',
            'AP_Math',
            'AP_Param',
            'GCS_MAVLink',
        ]
    )
